#spring.application.name=Course-Registration-System
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = dpg-d8sn8elckfvc7388ok2g-a:5432/course_reg_sym
#spring.datasource.username = course_register_user
#spring.datasource.password = npwSa5SxWAXmsVp4WZWRfFAOKh4kxs8T
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update

spring.application.name=Course-Registration-System

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8sn8elckfvc7388ok2g-a.oregon-postgres.render.com:5432/course_register
spring.datasource.username=course_register_user
spring.datasource.password=npwSa5SxWAXmsVp4WZWRfFAOKh4kxs8T

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#postgresql://course_register_user:npwSa5SxWAXmsVp4WZWRfFAOKh4kxs8T@dpg-d8sn8elckfvc7388ok2g-a/course_register
